### ISSUE TITLE
V1.4 question

### ISSUE THREAD

**Issue by maded2** [floobydust/65C02-SBC1#1]
hi,
    I've got v1.4 running on my SBC.  There's only a question about BURN_BYTE.  The source code say location $0000, which looks to me to be incorrect.  So I set it to $1000.  What is the correct address.

from the source code
BURN_BYTE	=	$0000	;Location in RAM for BYTE write routine

thanks,
eddie

**Comment by floobydust** [comment]
The BURN_BYTE location of $0000 is correct. Look at what the code is doing... a function of the Monitor is allow code to be programmed (or burned) into the EEPROM insitu (i.e., without removing it from the SBC). As the routine to program a byte is located in the EEPROM, it can't be executed from EEPROM! So, the routine is copied to page zero ($0000) and executed via a JSR $0000. On return, the ROM routine continues to the next memory location.
 You can obviously change it to another RAM location, but there's no need to, unless you have other code using the first 19 bytes of Page zero actively.
 KM

**Comment by maded2** [comment]
thanks for your quick reply.  I did move it to $1000.  As I've not planned to in-circuit flashing of the EEPROM then I just move the to the $1000 as the ca64 assembler don't like negative address (if I use the default $0000) due to the following line:

STA	BURN_BYTE-1,X	;Write code to RAM

**Comment by floobydust** [comment]
Well, different assemblers have different syntax for addressing. In this particular case, the assembler is assuming page zero addressing, which is a single byte operand. Problem is, a JSR can only use a 2-byte operand for a 16-bit address.

 I've been using the WDC Tools for the last 7 years. It's not perfect, but none of the available assembler/linker packages are. In any case, WDC Tools is a free download and all of my source code will assemble and link properly when used with WDC Tools.

 Also note that the Xmodem download utility in the monitor will automatically recognize Motorola S-Record files and process them during download. However, it ONLY works with the WDC S19 record format. The source code can be modified for other S-record formats, but as I'm sticking with the WDC Tools, I've no need to change it.

 Do send a few pics of your SBC... and also considering posting at 6502.org. I'm a member there as well and there's a lot of great projects posted there.

 KM

**Comment by maded2** [comment]
you can see my build on my github repo.

https://github.com/maded2/6502

**Comment by maded2** [comment]
have posted to 6502.org
