### ISSUE TITLE
strange disassembly output

### ISSUE THREAD

**Issue by maded2** [floobydust/65C02-SBC1#2]
hi, I've a simple hello world which works in the CO2Monitor.  I assembled it using ca65 and transferred to the SBC using xmodem and the code runs fine.   But when I try to use the built-in disassembler (Ctrl-D), I get strange output.

```
          .segment "CODE"

CHROUT = $FF4E

				PHA
				PHX
				LDX #$00
LOOP		LDA	HELLO_WORLD,X	;Get BIOS init msg (4)
				BEQ	EXIT	;If zero, msg done, goto cold start monitor (2/3)
				JSR	CHROUT	;Send to console (6)
				INX	;Increment Index (2)
				BRA	LOOP	;Loop back until done (3)
EXIT
				PLX
				PLA
				RTS

HELLO_WORLD
				.byte	$0D,$0A
				.byte	"Hello World"
				.byte	$0D,$0A
				.byte	$00	;Terminate string
```

output

```
C02Monitor (c)2016 K.E.Maier                                                                                            
Version 1.4                                                                                                             
;-XMODEM Loader, <Esc> to abort, or
Load Address/S-Record Offset:$2000                                                                                      

Download Complete!

;-G $2000
Hello World

;-G $2000
Hello World

;-
Disassembly from addr:$2000
$2000  48            GQD  
$2001  DA            MID  
$2002  A2  00        MHS  #$00
$2004  BD  12  20    GPS  $2012,X
$2007  F0  06        SOK  $200F
$2009  20  4E  FF    CXM  $FF4E
$200C  E8            ]HH  
$200D  80  F5        WOM  $2004
$200F  FA            MID  
$2010  68            GQD  
$2011  60            LAM  
$2012  0D  0A  48    WQA  $480A
$2015  65  6C        H?G  $6C
$2017  6C  6F  20    SHL  ($206F)
$201A  57  6F        OYL5 $6F
$201C  72  6C        H?G  ($6C)
$201E  64  0D        MYQ  $0D
$2020  0A            BGI  A
$2021  00  1A        Z?M  #$1A
$2023  1A            X@H  A
$2024  1A            X@H  A
$2025  1A            X@H  A
```

**Comment by floobydust** [comment]
It looks like the Mnemonic table is corrupted. What did you use to assemble the C02 Monitor code with? If you look at the source file, the Mnemonic table is at the end. Each Mnemonic is a 16-bit value, where 5-bits are used for each letter. If the assembler you used swapped bits around, you'll have a corrupted table and the decoded characters will be incorrect.
 Here's a partial listing of the correctly assembled Mnemonic data... if your assembler doesn't generate the table data the same, then there's your problem. The actual data is in **BOLD** Hex vales after the 16-bit hex address, i.e., $00 $00 $11 $48 $13 $CA, etc.

  2611 00:F35A: **00 00**                .DBYTE  %0000000000000000       ;???    $00
  2612 00:F35C: **11 48**                .DBYTE  %0001000101001000       ;ADC    $02
  2613 00:F35E: **13 CA**                .DBYTE  %0001001111001010       ;AND    $04
  2614 00:F360: **15 1A**                .DBYTE  %0001010100011010       ;ASL    $06
  2615 00:F362: **18 E6**                .DBYTE  %0001100011100110       ;BBR    $08
  2616 00:F364: **18 E8**                .DBYTE  %0001100011101000       ;BBS    $0A
  2617 00:F366: **19 08**                .DBYTE  %0001100100001000       ;BCC    $0C
  2618 00:F368: **19 28**                .DBYTE  %0001100100101000       ;BCS    $0E
  2619 00:F36A: **19 A4**                .DBYTE  %0001100110100100       ;BEQ    $10
  2620 00:F36C: **1A AA**                .DBYTE  %0001101010101010       ;BIT    $12
  2621 00:F36E: **1B 94**                .DBYTE  %0001101110010100       ;BMI    $14
  2622 00:F370: **1B CC**                .DBYTE  %0001101111001100       ;BNE    $16
  2623 00:F372: **1C 5A**                .DBYTE  %0001110001011010       ;BPL    $18
  2624 00:F374: **1C C4**                .DBYTE  %0001110011000100       ;BRA    $1A
  2625 00:F376: **1C D8**                .DBYTE  %0001110011011000       ;BRK    $1C
  2626 00:F378: **1D C8**                .DBYTE  %0001110111001000       ;BVC    $1E
  2627 00:F37A: **1D E8**                .DBYTE  %0001110111101000       ;BVS    $20

**Comment by maded2** [comment]
thanks, looks like ca65 convert the word to bidendian.  I manually transposed the word and it is now working fine.
